#!usr/bin/env bash
# Bash script that loops from 1 to 10

i="0"
while (("$i" < "10")); do

	if [ "$i" -eq 3 ]; then
		echo "bad luck"
	elif [ "$i" -eq 7 ]; then
		echo -e "good luck"
	else
		echo "Best School"
	fi

	((i++))

done
