#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 20 and handles certain iterations

i=0
while [ "$i" -le 20 ]; do
	case $i in
		3)
			echo "$i"
			echo "bad luck from China"
			;;
		8)
			echo "$i"
			echo "$i bad luck from Japan"
			;;
		16)
			echo "$i"
			echo "$i bad luck from Italy"
			;;
		*)
			echo "$i"
			;;
	esac
	((i++))
done
