#!/usr/bin/env bash
# changing configuration in /etc/hosts file
cp /etc/hosts ~/host.new
echo "127.0.0.2	localhost" >> ~/host.new
echo "8.8.8.8	facebook.com" >> ~/host.new
cp -f ~/host.new /etc/hosts
